### ISSUE TITLE
It's impossible to install pypy on MacOs M1

### ISSUE THREAD

**Issue by metya** [conda-forge/pypy-meta-feedstock#28] opened 2023-03-15 18:43 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

It's impossible to install pypy on Macos M1
There is no package for M1
If put `CONDA_SUBDIR=osx-64`before creating environment, then everything is alright.  

If not, there is the error

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
python=3.9
pypy -> python[version='3.6.12|3.6.12|3.7.10|3.7.10|3.7.12|3.8.12|3.8.13|3.8.16|3.9.16|3.9.12|3.9.10|3.7.9|3.6.9|3.6.9|3.6.9|3.6.9',build='4_73_pypy|5_73_pypy|5_73_pypy|0_73_pypy|1_73_pypy|0_73_pypy|3_73_pypy|2_73_pypy|1_73_pypy|0_73_pypy']
```

### Installed packages

```shell
empty environment
```

### Environment info

```shell
active environment : base
    active env location : /opt/homebrew/Caskroom/mambaforge/base
            shell level : 1
       user config file : /Users/metya/.condarc
 populated config files : /opt/homebrew/Caskroom/mambaforge/base/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.11.0.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.1=0
                          __unix=0=0
       base environment : /opt/homebrew/Caskroom/mambaforge/base  (writable)
      conda av data dir : /opt/homebrew/Caskroom/mambaforge/base/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/homebrew/Caskroom/mambaforge/base/pkgs
                          /Users/metya/.conda/pkgs
       envs directories : /opt/homebrew/Caskroom/mambaforge/base/envs
                          /Users/metya/.conda/envs
               platform : osx-arm64
             user-agent : conda/22.11.1 requests/2.28.2 CPython/3.11.0 Darwin/22.2.0 OSX/13.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by isuruf** [comment] 2023-03-15 21:29
Duplicate of https://github.com/conda-forge/pypy3.6-feedstock/issues/88

**Closed by isuruf** 2023-03-15 21:29 UTC
Labels: bug

**Comment by mattip** [comment] 2023-03-15 21:31
This is a duplicate of conda-forge/pypy3.6-feedstock#88 and conda-forge/miniforge#398. It would require rebuilding over 1500 packages for the new platform, many of which [do not build for PyPy](https://conda-forge.org/status/#pypy38). Currently there is no native CI support for arm64. Cross-compilation is slow and does not allow for testing, so it is a big commitment for conda-forge. In the mean time, in the two months since uploading the latest pypy 3.8 builds, there are [around 2000](https://anaconda.org/conda-forge/pypy3.8/files) macos downloads, and a similar [number for pypy3.9](https://anaconda.org/conda-forge/pypy3.9/files). It is not clear this small demand justifies the load on the volunteer conda-forge team.

Is there a reason you cannot use the x86_64 emulation on your machine for your work?

**Comment by metya** [comment] 2023-03-15 21:42
I see! Thank you for answers!
